PizzaNight\ManagementBundle\Entity\Attendee:
  type: entity
  table: null
  repositoryClass: PizzaNight\ManagementBundle\Repository\AttendeeRepository
  fields:
    event_id:
      type: integer
      id: true
    contact_id:
      type: integer
      id: true
    why:
      type: text
      nullable: true
    pizza:
      type: string
      length: 30
      nullable: true
    date:
      type: datetime
    slug:
      type: string
      length: 20
    status:
      type: smallint
    register_date:
      type: datetime
      nullable: true
  manyToOne:
    event:
      targetEntity: Event
      cascade:  {}
      mappedBy: id
    contact:
      targetEntity: Contact
      cascade:  {}
      mappedBy: id
  lifecycleCallbacks:
      prePersist: [ generateSlug ]
