PizzaNightAsistenteBundle:
    resource: "@PizzaNightAsistenteBundle/Controller/"
    type:     annotation
    prefix:   /

PizzaNightManagementBundle:
    resource: "@PizzaNightManagementBundle/Controller"
    type:     annotation
    prefix:   /

PizzaNightWebServiceBundle:
    resource: "@PizzaNightWebServiceBundle/Controller"
    type:     annotation
    prefix:   /api

PizzaNightIntranetBundle:
    resource: "@PizzaNightIntranetBundle/Controller"
    type:     annotation
    prefix:   /intranet

login_check:
    pattern:    /login_check

logout:
    pattern:    /logout