security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        in_memory:
            users:

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~

    access_control: