<?php

namespace PizzaNight\ManagementBundle\Repository;

use Doctrine\ORM\EntityRepository;
use PizzaNight\ManagementBundle\Entity\Attendee;
/**
 * AttendeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendeeRepository extends EntityRepository
{
    public function findEventAttendees(\PizzaNight\ManagementBundle\Entity\Event $event)
    {
        $query = $this->createQueryBuilder('a')
            ->where('a.event_id=:event_id AND a.status=:status')
            ->setParameter('event_id', $event->getId())
            ->setParameter('status', Attendee::STATUS_ACCEPTED)
            ->getQuery();

        return $query->getResult();
    }

    public function findNextSlug($event_id)
    {
        $attendees = $this->createQueryBuilder('a')
            ->where('a.event_id=:event_id AND a.status=:status')
            ->setParameter('event_id', $event_id)
            ->setParameter('status', Attendee::STATUS_IN_THE_EVENT)
            ->getQuery()
            ->getResult();

        if(count($attendees)>0) {
            return $attendees[mt_rand(0, count($attendees))-1]->getSlug();
        } else {
            return 'no attendees';
        }
    }
}