<?php

namespace PizzaNight\ManagementBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function findAllForAdminList($order_by_column='', $order_by_type='ASC') {
        $query = $this->createQueryBuilder('a');

        if($order_by_column!='') {
            $query->orderBy('a.' . $order_by_column, $order_by_type);
        } else {
            $query->orderBy('a.name', 'ASC');
        }

        return $query->getQuery()->getResult();
    }
}