<?php

namespace PizzaNight\ManagementBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findNextEvents($limit=0)
    {
        $query = $this->createQueryBuilder('e')
            ->where('e.date>:now')->setParameter('now' , date('Y-m-d H:i:s'));

        if($limit>0) {
            $query->setMaxResults($limit);
        }

        $query = $query
            ->orderBy('e.date', 'ASC')
            ->getQuery();

        return $query->getResult();
    }

}